data_cfg:
  dataset_name: CompanyFree
  dataset_root: /data1/all_data_pkl_new
  dataset_partition: ./all_data_20250912_add2503_noise.json
  num_workers: 1
  data_in_use: [True, False, False, False]
  remove_no_gallery: false
  test_dataset_name: CompanyFree

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: false
  restore_hint: 0
  save_name: SwinGait3D_B1122_C2_CompanyFree_SwinGait
  sampler:
    batch_shuffle: false
    batch_size: 1
    sample_type: all_ordered
    frames_all_limit: 720
  eval_func: evaluate_reduce_target
  metric: euc
  dataset_partition: ./all_data_20250912_add2503_noise.json
  save_json: show_result/company_free_swingait.json
  enable_save_csv: true
  split_eva: true
  tb_name: company_free_swingait
  transform:
    - type: BaseSilCuttingTransform

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true

model_cfg:
  model: SwinGait
  Backbone:
    mode: p3d
    in_channels: 1
    layers:
      - 1
      - 1
      - 2
      - 2
    channels:
      - 64
      - 128
  bin_num:
    - 15
  SeparateBNNecks:
    in_channels: 256
    class_num: 27534
    parts_num: 16

optimizer_cfg:
  lr: 0.0003
  solver: AdamW
  weight_decay: 0.02

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 100000000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true
  fix_BN: false
  log_iter: 100
  with_test: false
  optimizer_reset: true
  restore_ckpt_strict: false
  restore_hint: 0
  save_iter: 20000
  save_name: SwinGait3D_B1122_C2_CompanyFree_SwinGait
  sync_BN: true
  T_max_iter: 60000
  total_iter: 60000
  sampler:
    batch_shuffle: true
    batch_size:
      - 3
      - 16
    frames_num_fixed: 30
    frames_skip_num: 4
    sample_type: fixed_ordered
    type: TripletSampler
  transform:
    - type: Compose
      trf_cfg:
        - type: RandomPerspective
          prob: 0.2
        - type: BaseSilCuttingTransform
        - type: RandomHorizontalFlip
          prob: 0.2
        - type: RandomRotate
          prob: 0.2